# Generated by Django 5.0.2 on 2024-03-02 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_group_options_alter_lesson_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessProduct',
            new_name='Access',
        ),
    ]
